require 'rubygems'
gem 'activesupport', '~> 3'
require 'httparty'
require 'hashie'
require 'rash'
require 'will_paginate'
require 'will_paginate/collection'
require 'active_support/core_ext/array'

require 'rentjuicer/client'
require 'rentjuicer/response'
require 'rentjuicer/error'
require 'rentjuicer/lead'
require 'rentjuicer/listings'
require 'rentjuicer/listing'
require 'rentjuicer/neighborhoods'
